python.exe main.py\
    --image_dir data/LGK/images \
    --ann_path data/LGK/LGK_ann.json \
    --dataset_name LGK \
    --max_seq_length 60 \
    --threshold 3 \
    --epochs 100 \
    --batch_size 8 \
    --lr_ve 1e-4 \
    --lr_ed 5e-4 \
    --step_size 10 \
    --gamma 0.8 \
    --num_layers 3 \
    --seed 7580 \
    --beam_size 3 \
    --save_dir results/LGK/ \
